Repository sahityagaurav4210/book-junction-admin, pull requests merged in 2024-04, with the labels that each got.

#2 13/04/2024 - feat: added @book-junction/env-loader package
  app.js
  package-lock.json
  package.json
Labels: enhancement

#5 14/04/2024 - fix: removed unneccessary packages
  app.js
  package-lock.json
  package.json
Labels: enhancement

#6 14/04/2024 - fix: moved nodemon to dev dependancy and fixed app scripts accordingly
  package-lock.json
  package.json
Labels: enhancement

#9 14/04/2024 - feat: changed the login api response from string to json
  app.js
Labels: enhancement

#11 15/4/2024 - feat: added commit message generator script
  package-lock.json
  package.json
  scripts/commit_msg_generator.script.mjs
Labels: enhancement

#13 16 4 2024/12 fix appjs file part 1
  .gitignore
  app.js
  config/index.js
  exceptions/AppNotInitializedException.js
  exceptions/Types.js
Labels: enhancement

#17 18/4/2024 - feat: Added system variable check functionality
  app.js
  config/index.js
  constants.js
  exceptions/EnvNotLoadedException.js
  exceptions/Types.js
Labels: enhancement

#18 logout functionality fixed
  static/js/cp.js
  views/cp.pug
Labels: enhancement

#19 22/4/2024 - fix: minor bug issue fix
  static/js/cp.js
Labels: bug

#21 24/4/2024 - fix: removed the logout operation on page reload
  static/js/cp.js
  static/js/login.js
  views/cp.pug
Labels: bug

#28 25/4/2024 - feat: added necessary middlewares to login api
  .vscode/settings.json
  controllers/authentication.controller.js
  middlewares/authentication.middleware.js
  middlewares/index.js
  routes/authentication.route.js
  static/css/login.css
  views/login.pug
Labels: enhancement

#30 25/4/2024 - refac: removed unnecessary logs from files
  controllers/authentication.controller.js
  middlewares/authentication.middleware.js
Labels: refactoration

#31 25/4/2024 - feat: renamed static folder
  config/index.js
  public/api/index.js
  public/css/alignment.css
  public/css/cp.css
  public/css/login.css
  public/css/update.css
  public/css/view.css
  public/helpers/index.js
  public/helpers/notification_type.helpers.js
  public/images/add.png
  public/images/select.png
  public/images/trash.png
  public/images/update.png
  public/js/cp.js
  public/js/login.js
  public/js/update.js
  public/js/view.js
  public/utils/index.js
  views/cp.pug
  views/login.pug
  views/update.pug
  views/view.pug
Labels: enhancement

#38 27/4/2024 - feat: added necessary middlewares to check api
  controllers/authentication.controller.js
  routes/authentication.route.js
Labels: enhancement

#39 29/4/2024 - fix: minor code issue
  config/index.js
Labels: bug, enhancement

#40 29/4/2024 - feat: added 404 page
  controllers/welcome.controller.js
  public/css/style.css
  public/css/utils.css
  public/fonts/Poppins-Regular.ttf
  public/fonts/Roboto-Regular.ttf
  public/helpers/index.js
  public/images/pages/404.avif
  public/images/social_media/email.png
  public/images/social_media/instagram.png
  public/images/social_media/linkedin.png
  public/js/404.js
  routes/welcome.route.js
  views/404.pug
Labels: enhancement, proposal
